// Generated by CoffeeScript 1.6.3
(function() {
  var Tag;

  Tag = require('../models/tag.js');

  exports.index = function(req, res) {
    return Tag.find({}, function(err, tags) {
      if (err) {
        req.flash('error', err);
        return res.redirect('/');
      }
      return res.render('tags/index', {
        title: '标签',
        user: req.user,
        tags: tags,
        success: req.flash('success').toString(),
        error: req.flash('error').toString()
      });
    });
  };

  exports["new"] = function(req, res) {
    var tag;
    tag = {
      key: '',
      name: '',
      content: ''
    };
    return res.render('tags/new', {
      title: '添加',
      user: req.user,
      currentLink: 'MICRO',
      tag: tag,
      success: req.flash('success').toString(),
      error: req.flash('error').toString()
    });
  };

  exports.edit = function(req, res) {
    var id;
    id = req.params.id;
    console.log('id' + id);
    return Tag.findOne({
      '_id': id
    }, function(err, tag) {
      if (err) {
        req.flash('error', err);
        return res.redirect('/tags');
      }
      return res.render('tags/edit', {
        title: '修改',
        user: req.user,
        currentLink: 'MICRO',
        tag: tag,
        success: req.flash('success').toString(),
        error: req.flash('error').toString()
      });
    });
  };

  exports.doEdit = function(req, res) {
    var id, tagData;
    tagData = req.body.tag;
    id = tagData._id;
    delete tagData._id;
    console.log(tagData);
    return Tag.update({
      _id: id
    }, tagData, {
      multi: true
    }, function(err, numberAffected, raw) {
      if (err) {
        console.log(err);
        req.flash('error').toString();
        return res.redirect('/tags/' + tagData._id + '/edit');
      } else {
        console.log('success');
        console.log(numberAffected + raw);
        req.flash('success', 'tag 修改成功！');
        return res.redirect('/tags');
      }
    });
  };

  exports.create = function(req, res) {
    var tag, tagData;
    tagData = req.body.tag;
    tag = new Tag(tagData);
    console.log(tag);
    return tag.save(function(err) {
      if (err) {
        return res.render('tags/new', {
          title: '添加',
          tag: tag,
          currentLink: 'MICRO',
          success: req.flash('success').toString(),
          error: req.flash('error').toString()
        });
      } else {
        req.flash('success', 'tag 添加成功！');
        return res.redirect('/tags');
      }
    });
  };

  exports.destroy = function(req, res) {
    return Tag.remove({
      _id: req.body.tagId
    }, function(err) {
      if (err) {
        req.flash('error', '删除失败！');
        return res.redirect('/tags/');
      } else {
        req.flash('success', '删除成功！');
        return res.redirect('/tags/');
      }
    });
  };

}).call(this);
